---
- name: 'Pull registry image'
  connection: 'local'
  run_once: yes
  vars:
    argv:
      - 'scripts/podman_check_pull.bash'
      - 'registry:{{ registry_tag }}'
  args:
    executable: '/bin/bash'
  script: '{{ argv | join(" ") }}'

- name: 'Start registry container'
  connection: 'local'
  run_once: yes
  vars:
    argv:
      - 'scripts/registry_start_run.bash'
      - '{{ registry_tag }}'
      - '{{ item.name }}'
      - '{{ item.port }}'
  args:
    executable: '/bin/bash'
  loop: '{{ mirrors }}'
  script: '{{ argv | join(" ") }}'

# can't install the rule, but can inform about it
# needs:
# sudo iptables -I INPUT 1 -ptcp --dport 5000:5002 -j ACCEPT
- name: 'Test if firewall port is blocked'
  #register: 'reg_ports_open'
  delegate_to: '{{ groups.primaries | first }}'
  loop: '{{ mirrors }}'
  wait_for:
    host: '{{ hostvars[groups.builder | first].ansible_host }}'
    port: '{{ item.port }}'
    timeout: 1
...
# vim: set filetype=yaml:
