---
- name: 'Output service name'
  run_once: yes
  debug:
    var: 'item'

- name: 'Remove down file'
  when:
    - 'has_runit'
  file:
    dest: '/etc/sv/{{ item }}/down'
    state: 'absent'

- name: 'Start runit service'
  when:
    - 'has_runit'
  runit:
    name: '{{ item }}'
    state: 'started'

- name: 'Enable systemd service'
  when:
    - 'has_systemd'
  command:
    argv:
      - 'systemctl'
      - 'enable'
      - '{{ item }}'
#  systemd:
#    name: '{{ item }}'
#    #enabled: yes  # apparently, doesn't work
#    state: 'enabled'

# TODO: possibly add retries?
- name: 'Start systemd service'
  when:
    - 'has_systemd'
  systemd:
    name: '{{ item }}'
    #enabled: yes  # apparently, doesn't work
    state: 'started'
...
# vim: set filetype=yaml:
