---
- name: 'Reload systemd files'
  when:
    - 'has_systemd'
  systemd:
    daemon_reload: yes

- name: 'Loop over services'
  loop: '{{ services }}'
  include_tasks: 'loop.yml'

- name: 'Reboot'
  reboot:
...
# vim: set filetype=yaml:
