---
- name: 'Reload systemd files'
  when:
    - 'has_systemd'
  systemd:
    daemon_reload: yes

- name: 'Loop over services'
  loop: '{{ services }}'
  include_tasks: 'loop.yml'

- name: 'Reboot'
  reboot:
    # workaround for really weird bug
    reboot_command: 'reboot'
...
# vim: set filetype=yaml:
