---
- name: 'Validation checks'
  hosts: 'all'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'checks'
    - 'always'
  roles:
    - 'ansible_groups_check'   # this doesn't work now?
    - 'ansible_version_check'  # not sure this is needed
    - 'ansible_vault_check'    # not sure this is needed either
    - 'builder_registry_check'
  tasks:
    # to circumvent know bugs in libvirtd :(
    - name: 'Detect libvirtd version'
      connection: 'local'
      run_once: yes
      set_fact:
        libvirtd_version: '{{ lookup("lines", "libvirtd -V | cut -d\  -f3") }}'
    - name: 'Output libvirtd version'
      connection: 'local'
      run_once: yes
      debug:
        var: 'libvirtd_version'
...
# vim: set filetype=yaml:
