---
- name: 'Checks'
  import_playbook: 'checks.yml'

# useful to find "empty" files: $ find roles/ -size 35c -type f
# useful to find actually empty files: $ find roles/ -size 0 -type f
# useful to find empty directories: $ find roles/ -empty -type d

# TODO #12 make vm - disk_setup, virsh_setup ?
# see roles/foreman_setup/templates/vmspec.xml.j2 (might be symlinks
# from other roles?)

- name: 'Basic setup of nodes and Foreman host'
  hosts: 'foreman:nodes'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'foreman'
    - 'nodes'
  roles:
    - role: 'xbps_setup'
      when:
        - 'has_xbps'
    - role: 'yum_setup'
      when:
        - 'has_yum'
    - role: 'apt_setup'
      when:
        - 'has_apt'
    - 'rsyslog_setup'
    - role: 'service_start'
      vars:
        services:
          - 'rsyslog'
    - 'logrotate_setup'
    - 'openssh_server_setup'
    - role: 'selinux_setup'
      when:
        - 'mandatory_access_control == "selinux"'
    - role: 'apparmor_setup'
      when:
        - 'mandatory_access_control == "apparmor"'
    - 'grub_setup'
    - 'services_tidy'
    - 'files_tidy'
    - role: 'iptables_setup'
      when:
        - 'has_iptables'  # is this right? maybe redesign this role
    - role: 'service_start'
      when:
        - 'has_iptables'
      vars:
        services:
          - 'iptables'
    - role: 'dhcpcd_setup'
      when:
        - 'has_dhcpcd'
    - role: 'service_start'
      when:
        - 'has_dhcpcd'
      vars:
        services:
          - 'dhcpcd'
    - role: 'ifcfg_setup'
      when:
        - 'not has_dhcpcd'
        - 'has_sysconfig'
    - role: 'networking_setup'
      when:
        - 'not has_dhcpcd'
        - 'not has_sysconfig'
    - 'chrony_setup'
# Ubuntu hates chrony apparently?
# TODO #13: fix
#    - role: 'service_start'
#      vars:
#        services:
#          - 'chronyd'
    #- 'do_nothing'
    #- 'fail_egregiously'

- name: 'Prepare Foreman'
  hosts: 'foreman'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'foreman'
    - 'never'  # remove 'never' when foreman_setup role is bulletproof
  roles:
    - 'foreman_setup'

- name: 'Prepare builder'
  hosts: 'builder'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'builder'
    - 'never'  # only run when setting up the build host initially
  roles:
    - 'k3s_tarball_prep'
    - 'images_pull'

- name: 'Continue node preparation'
  hosts: 'nodes'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'prepare_nodes'
  roles:
    - 'sysctl_setup'
    - 'swap_disable'
    - 'iscsi_setup'
    - role: 'service_start'
      vars:
        services:
          - 'iscsi'
          - 'iscsid'
    - 'hosts_file_setup'

- name: 'Install k3s'
  hosts: 'nodes'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'install_nodes'
  roles:
    - 'k3s_service_setup'
    - role: 'k3s_generate_token'
      when:
        - 'is_primary'
    - 'k3s_service_add_token'
    - role: 'service_start'
      vars:
        services:
          - 'k3s'
# TODO: fix reboot role
#    - role: 'host_reboot'
#      when:
#        - 'is_primary'
    - 'k3s_service_configure'
#    - role: 'host_reboot'
#      when:
#        - 'not is_primary'
    - 'nodes_check'
    # TODO: add firewall check here
    - 'calico_install'
    - 'helm_install'
    - 'metallb_install'
    - 'ingress-nginx_install'
    - 'longhorn_install'

# TODO #14: continue k3s setup, metallb, etc. bootstrap and appinstall

- name: 'Install apps'
  hosts: 'primaries'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'install_apps'
  roles:
    - 'cert-manager_install'
#    - 'kerberos_install'
    - 'openldap_install'
    - 'postgresql_install'

- name: 'Post-install auto-snapshot'
  hosts: 'foreman:nodes'
  connection: 'local'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'foreman'
    - 'nodes'
    - 'snapshot'
  vars:
    snapshot_name: 'post-install-autosnap'
  roles:
    - 'snapshot_delta_commit'
    - 'snapshot_delta_create'
...
# vim: set filetype=yaml:
