---
- name: 'Checks'
  import_playbook: 'checks.yml'

# Note: for HA embedded etcd, we MUST use an odd number of master nodes (also, at least 3).
# https://docs.k3s.io/datastore/ha-embedded

# Work: while on libvirt8, run with "--skip-tags=broken_on_libvirt_8"

- name: 'Spread versions'
  hosts: 'all'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    # to circumvent know bugs in libvirtd :(
    - 'libvirtd_version_get'

# useful to find "empty" files: $ find roles/ -size 35c -type f
# useful to find actually empty files: $ find roles/ -size 0 -type f
# useful to find empty directories: $ find roles/ -empty -type d

# TODO #12 make vm - disk_setup, virsh_setup ?
# see roles/foreman_setup/templates/vmspec.xml.j2 (might be symlinks
# from other roles?)

- name: 'Basic setup of nodes'
  hosts: 'nodes'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
  roles:
    - role: 'xbps_setup'
      when:
        - 'has_xbps'
    # Ubuntu libvirtd has bugs :(
    - role: 'yum_setup'
      when:
        - 'has_yum'
        - 'libvirtd_version is version("9.0", ">")'
    - role: 'apt_setup'
      when:
        - 'has_apt'
    - role: 'rsyslog_setup'
      when:
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - role: 'service_start'
      vars:
        services:
          - 'rsyslog'
    - role: 'logrotate_setup'
      when:
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - 'openssh_server_setup'
    - role: 'selinux_setup'
      when:
        - 'mandatory_access_control == "selinux"'
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - role: 'apparmor_setup'
      when:
        - 'mandatory_access_control == "apparmor"'
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - 'grub_setup'
    - 'services_tidy'
    - 'files_tidy'
    - role: 'iptables_setup'
      when:
        - 'has_iptables'  # is this right? maybe redesign this role
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - role: 'service_start'
      when:
        - 'has_iptables'
      vars:
        services:
          - 'iptables'
    - role: 'dhcpcd_setup'
      when:
        - 'has_dhcpcd'
    - role: 'service_start'
      when:
        - 'has_dhcpcd'
      vars:
        services:
          - 'dhcpcd'
    - role: 'ifcfg_setup'
      when:
        - 'not has_dhcpcd'
        - 'has_sysconfig'
    - role: 'networking_setup'
      when:
        - 'not has_dhcpcd'
        - 'not has_sysconfig'
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
    - role: 'chrony_setup'
      when:
        - 'not has_yum
           or libvirtd_version is version("9.0", ">")'
# Ubuntu hates chrony apparently?
# TODO #13: fix
#    - role: 'service_start'
#      vars:
#        services:
#          - 'chronyd'

#- name: 'Prepare Foreman'
#  hosts: 'foreman'
#  become: yes
#  gather_facts: no
#  handlers:
#    - import_tasks: 'handlers/main.yml'
#  tags:
#    - 'foreman'
#    - 'never'  # remove 'never' when foreman_setup role is bulletproof
#  roles:
#    - 'foreman_setup'

- name: 'Prepare builder'
  hosts: 'builder'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'builder'
    - 'never'  # only run when setting up the build host initially
  roles:
    - 'k3s_tarball_prep'
    - 'images_pull'

- name: 'Continue node preparation'
  hosts: 'nodes'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'prepare_nodes'
  roles:
    - 'limits_setup'
    - 'sysctl_setup'
    - 'swap_disable'
    - 'iscsi_setup'
    - role: 'service_start'
      vars:
        services:
          - 'iscsi'
          - 'iscsid'
    - 'hosts_file_setup'

- name: 'Install k3s'
  hosts: 'nodes'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'install_nodes'
  roles:
    - 'k3s_service_setup'
    - 'k3s_service_configure'

- name: 'Generate unique cluster token'
  hosts: 'primaries'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  vars:
    services:
      - 'k3s'
  roles:
    - 'k3s_generate_token'
    - 'service_enable_and_reboot'

- name: 'Slurp cluster token'
  hosts: 'secondaries:agents'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  vars:
    services:
      - 'k3s'
  roles:
    - 'k3s_service_add_token'
    - 'service_enable_and_reboot'

- name: 'Copy kube config to builder'
  hosts: 'primaries'
  run_once: yes  # note! run_once
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  roles:
    - 'k3s_copy_config'

# TODO?: No scheduling on control planes (except local-path, coredns and metrics server):
# kubectl taint node k3s-mother-0?.k3s.lab k3s-controlplane=true:NoSchedule

# Edit deployments/local-path-provisioner,
# deployments/coredns,
# deployments/metrics-server
#      tolerations:
#      - effect: NoExecute
#        operator: Exists
#      - effect: NoSchedule
#        operator: Exists

- name: 'Configuration and infrastructure'
  hosts: 'primaries'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  vars:
    patches:  # for kubectl_patch
      - file: 'coredns-memory'
        kind: 'deployments.app'
        name: 'coredns'
        namespace: 'kube-system'
    manifests:  # for kubectl_apply
      - 'coredns-errors'
    deployments_for_restart:
      - name: 'coredns'
        namespace: 'kube-system'
  roles:
    - 'nodes_check'
    - 'k3s_apitokens_generate'
    - role: 'helm_install'
      become: yes
    - 'kubectl_patch'
    - 'kubectl_apply'
    - 'kubectl_rollout_restart'
    - 'calico_install'
    - 'infra_check'
    - 'cert-manager_install'
    - 'metallb_install'
    - 'ingress-nginx_install'  # requires cert-manager and metallb
    - do_nothing
    - 'longhorn_install'  # requires ingress-nginx

- name: 'Post-install auto-snapshot'
  hosts: 'nodes'
  connection: 'local'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'snapshot'
  vars:
    snapshot_name: 'post-install-autosnap'
  roles:
    - 'snapshot_delta_commit'
    - 'snapshot_delta_create'

- name: 'Install apps'
  hosts: 'primaries'
  become: yes
  gather_facts: yes
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'nodes'
    - 'install_apps'
  roles:
    - do_nothing
    - 'benthos_install'
    - fail_egregiously
    - 'vault_install'
    - 'kerberos_install'
    - 'openldap_install'
    - 'postgresql_install'
    - 'prometheus_install'
    - 'grafana_install'
...
# vim: set filetype=yaml
