---
- name: 'Start all hosts'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'start'
  tasks:
    - register: 'reg_start'
      vars:
        e_already: 'Domain is already active'
      loop: '{{ groups.all | difference(groups.builder) }}'
      changed_when:
        - 'reg_start.rc == 0'
        - 'e_already not in reg_start.stderr'
      failed_when:
        - 'reg_start.rc != 0'
        - 'e_already not in reg_start.stderr'
      command:
        argv:
          - 'virsh'
          - 'start'
          - '{{ item }}.{{ domain }}'

- name: 'Start registries'
  hosts: 'primaries'
  become: no
  gather_facts: no
  handlers:
    - import_tasks: 'handlers/main.yml'
  tags:
    - 'start'
  roles:
    - 'builder_registry_check'
...
# vim: set filetype=yaml:
