---
- name: 'Configure IP pools'
  args:
    stdin: '{{ lookup("template", "ip_pool.yaml.j2") }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'apply'
      - '-f'
      - '-'
...
# vim: set filetype=yaml:
