---
# https://t.ly/m3ZQe

- name: 'Report chart name'
  become: no
  connection: 'local'
  run_once: yes
  debug:
    msg: 'Installing {{ chart_name }}...'

# TODO: Check if chart already exists, skip repo business if so
# TODO: Three commands in a row, replace with script?
# Start on builder, then go to node
- name: 'Add helm repo'
  become: no
  connection: 'local'
  run_once: yes
  vars:
    e_already: 'already exists with the same configuration'
    local_helm_binary: '/usr/sbin/helm'
  environment:
    NO_PROXY: '*'
  block:
    - name: 'Add helm repo'
      command:
        argv:
          - '{{ local_helm_binary }}'
          - 'repo'
          - 'add'
          - '{{ repo_name }}'
          - '{{ repo_url }}'

    - name: 'Update helm repo state'
      command:
        argv:
          - '{{ local_helm_binary }}'
          - 'repo'
          - 'update'

    - name: 'Download helm chart'
      command:
        argv:
          - '{{ local_helm_binary }}'
          - 'fetch'
          - '-d'
          - '{{ blob_stage_dir }}'
          - '--version'
          - '{{ chart_version }}'
          #- '--verify'  # hmm, add this?
          - '{{ repo_name }}/{{ chart_name }}'

- name: 'Copy in helm chart'
  vars:
    chart_tarball: '{{ blob_stage_dir }}/{{ chart_name }}-{{ chart_version }}.tgz'
  copy:
    src: '{{ chart_tarball }}'
    dest: '{{ blob_tmp_dir }}/'

# Switch to node, so path is different
- name: 'Install helm chart (!!atomic!!)'
  register: 'reg_install'
  run_once: yes  # anywhere, but only once
  vars:
    e_already: 'cannot re-use a name that is still in use'
    remote_helm_binary: '{{ k3s_binary_dir }}/helm'
    cmd:
      - '{{ remote_helm_binary }}'
      - 'install'
      - '--namespace'
      - '{{ chart_namespace }}'
      - '--create-namespace'
      - '--atomic'
      - '--timeout={{ chart_install_timeout }}'
      - '{{ chart_name }}'
      - '/dev/shm/{{ chart_tarball | basename }}'
    chart_tarball: '{{ blob_stage_dir }}/{{ chart_name }}-{{ chart_version }}.tgz'
  failed_when:
    - 'reg_install.rc != 0'
    - 'e_already not in reg_install.stderr'
  command:
    argv: '{{ cmd + (chart_extra_args | default([])) }}'
...
# vim: set filetype=yaml:
