---
dependencies:
  - vars:
      chart_repo_name: 'longhorn'
      chart_repo_url: 'https://charts.longhorn.io'
      chart_namespace: 'longhorn-system'
      chart_name: 'longhorn'
      chart_version: '{{ longhorn_version }}'
      chart_install_timeout: '{{ longhorn_install_timeout }}'
      chart_values: 'longhorn_values.yml'
    role: 'meta_chart_install_2'
  - vars:
      ingress_prefix: 'longhorn'
      ingress_namespace: 'longhorn-system'
      ingress_service: 'longhorn-frontend'
      ingress_user: 'breakglassbackdoor'
    role: 'meta_ingress_create'
  # TODO: remove this meta and use the built-in version
  # in the Longhorn values file; search for "ingressClassName"
...
# vim: set filetype=yaml
