---
dependencies:
  - vars:
      repo_name: 'longhorn'
      repo_url: 'https://charts.longhorn.io'
      chart_name: 'longhorn'
      chart_version: '{{ longhorn_version }}'
      chart_namespace: '{{ longhorn_namespace }}'
      chart_install_timeout: '{{ longhorn_install_timeout }}'
    role: 'meta_helm_chart_install'
...
# vim: set filetype=yaml:
