---
# Don't delete Helm-managed items, it might throw a wobbly or just put them back

# Edit DITs, eg. manager user, base DN, etc.

- name: 'Patch service'
  vars:
    patch: '{"spec":{"type":"LoadBalancer"}}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'patch'
      - 'service/openldap-stack-ha'
      - '-n'
      - '{{ openldap_namespace }}'
      - '-p'
      - '{{ patch }}'
...
