---
all:
  vars:
    subnet: '10.7.6.0/24'
    domain: 'dreamtrack.net'
    # "host id" of the subnet gateway
    gateway_host_id: '254'

os_voidlinux:
  hosts:
    gang-mother-01:
      host_id: '212'
    gang-mother-02:
      host_id: '213'
    gang-mother-03:
      host_id: '214'

foreman:
  hosts:
    foreman-02:
  vars:
    foreman_dhcp_range_start_id: '175'
    foreman_dhcp_range_end_id: '195'
    foreman_reverse_zone: '{{ subnet | reverse_zone }}'

primaries:
  hosts:
    gang-mother-01:

secondaries:
  hosts:
    gang-mother-02:

agents:
  hosts:
    gang-mother-03:
...
# vim: set filetype=yaml:
