---
dependencies:
  - vars:
      repo_name: 'ingress-nginx'
      repo_url: 'https://kubernetes.github.io/ingress-nginx'
      chart_name: 'ingress-nginx'
      chart_version: '{{ ingress_nginx_version }}'
      chart_namespace: '{{ ingress_nginx_namespace }}'
      chart_install_timeout: '{{ ingress_nginx_install_timeout }}'
    role: 'meta_helm_chart_install'
...
# vim: set filetype=yaml:
