---
- name: 'Cordon node'
  delegate_to: '{{ groups.primaries | first }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'cordon'
      - '{{ inventory_hostname }}'

- name: 'Drain node'
  delegate_to: '{{ groups.primaries | first }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'drain'
      - '{{ inventory_hostname }}'
      - '--ignore-daemonsets'

- name: 'Kill remaining jobs'
  command:
    argv:
      - '/usr/local/bin/k3s-killall.sh'

- name: 'Delete node'
  delegate_to: '{{ groups.primaries | first }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'delete'
      - 'node/{{ inventory_hostname }}'

- name: 'Remove k3s'
  command:
    argv:
      - '/usr/local/bin/k3s-uninstall.sh'
...
# vim: set filetype=yaml:
