---
is_primary: '{{ inventory_hostname in groups.primaries }}'
k3s_extra_opts: '{{ [] if is_primary else k3s_secondary_args }}'
k3s_master_domain: 'https://{{ groups.primaries | first }}.{{ domain }}'
k3s_service_args:
  - 'server'
  - '--disable=servicelb'
  - '--disable=traefik'
  - '--flannel-backend=none'
  - '--disable-network-policy'
  - '--cluster-cidr=192.168.0.0/16'
  - '--write-kubeconfig-mode=0644'
  - '--cluster-init'
k3s_service_opts: '{{ k3s_service_args + k3s_extra_opts }}'
k3s_service_opts_str: '{{ k3s_service_opts | join(" ") }}'
k3s_secondary_args:
  - '--server={{ k3s_master_domain }}:6443'
  - '--token={{ server_token.strip() }}'
pre_reboot_delay_s: 10
post_reboot_delay_s: 10
settle_delay_s: 30
...
# vim: set filetype=yaml:
