---
# TODO: seems like this could be meta'd
- name: 'Apply manifest'
  environment:
    stdin: '{{ lookup("template", "benthos.yml.j2") }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'apply'
      - '-f'
      - '-'
...
# vim: set filetype=yaml:
