---
- name: 'Export environment'
  register: 'reg_environment'
  vars:
    cmd:
      - 'scripts/env_dump.bash'
  args:
    executable: '/bin/bash'
  script: '{{ cmd | join(" ") }}'

- name: 'Delete environment settings'
  file:
    path: '{{ environment_file }}'
    state: 'absent'

- name: 'Touch environment settings'
  file:
    path: '{{ environment_file }}'
    state: 'touch'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Create environment settings'
  when: '"_PROXY" in item
         or "_proxy" in item
         or "K3S" in item
         or "CONTAINERD" in item'
  loop: '{{ reg_environment.stdout_lines }}'
  lineinfile:
    line: '{{ item }}'
    dest: '{{ environment_file }}'
    create: yes

- name: 'Generate API tokens'
  register: 'reg_api_tokens'
  when:
    - 'is_primary'
  args:
    stdin: '{{ lookup("template", "api_tokens.yaml.j2") }}'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'apply'
      - '-f'
      - '-'
...
# vim: set filetype=yaml:
