---
dependencies:
  - vars:
      chart_repo_name: 'bitnami'
      chart_repo_url: 'https://charts.bitnami.com/bitnami'
      chart_namespace: 'metallb-system'
      chart_name: 'metallb'
      chart_version: '{{ metallb_version }}'
      #chart_install_timeout: '{{ metallb_install_timeout }}'
    role: 'meta_chart_install_2'
...
# vim: set filetype=yaml
