---
- name: 'Copy kube config to builder'
  vars:
    conf_file: '/tmp/cluster.conf'
  block:
    - name: 'Copy kube config'
      fetch:
        src: '/etc/rancher/k3s/k3s.yaml'
        dest: '{{ conf_file }}'
        flat: yes

    - name: 'Modify kube config'
      connection: 'local'
      replace:
        regexp: '^    server: https://127.0.0.1:6443$'
        replace: '    server: https://{{ ansible_host }}:6443'
        path: '{{ conf_file }}'

    - name: 'Symlink to kube config'
      connection: 'local'
      file:
        state: 'link'
        force: yes
        src: '{{ conf_file }}'
        dest: '~/.kube/config'
...
# vim: set filetype=yaml:
