---
dependencies:
  - vars:
      # ? not official
      repo_name: 'helm-openldap'
      repo_url: 'https://jp-gouin.github.io/helm-openldap'
      chart_name: 'openldap-stack-ha'
      chart_version: '{{ openldap_version }}'
      chart_namespace: '{{ openldap_namespace }}'
      chart_install_timeout: '{{ openldap_install_timeout }}'
    role: 'meta_helm_chart_install'
...
# vim: set filetype=yaml:
