---
dependencies:
  - vars:
      repo_name: 'bitnami'
      repo_url: 'https://charts.bitnami.com/bitnami'
      chart_name: 'openldap'
      chart_version: '{{ openldap_version }}'
      chart_namespace: '{{ openldap_namespace }}'
      chart_install_timeout: '{{ openldap_install_timeout }}'
    role: 'meta_helm_chart_install'
...
# vim: set filetype=yaml:
