---
dependencies:
  - vars:
      chart_repo_name: '../tinyldap/helm'
      chart_namespace: 'openldap-system'
      chart_name: 'tinyldap'
      chart_version: '0.0.1'
      chart_values: 'tinyldap_values.yml'
      chart_local: yes
    role: 'meta_chart_install_2'
...
# vim: set filetype=yaml
