---
all:
  vars:
    vm_disk_location: '/home/adam.richardson/.local/share/libvirt/images'
    vm_net_bridge_name: 'core_bridge'
    subnet: '10.20.0.0/24'
    domain: 'k3s.lab'
    gateway_host_id: '253'
    is_virtual: yes

os_rhel:
  vars:
    packages_disc_dir: '/home/adam.richardson/Downloads'
    packages_disc: '{{ packages_disc_dir }}/rhel-8.6-x86_64-dvd.iso'
  hosts:
    k3s-mother-01:
      host_id: '101'
    k3s-mother-02:
      host_id: '102'
    k3s-mother-03:
      host_id: '103'
    k3s-child-01:
      host_id: '111'
    k3s-child-02:
      host_id: '112'
    k3s-child-03:
      host_id: '113'

os_voidlinux:
  hosts: { }

os_ubuntu:
  hosts:
    # is devlaptop068
    build-1:
      host_id: '253'
    # Foreman needs its own environment. Stick it in an Ubuntu VM.
    # is xenial-playground
    #foreman-1:
    #  host_id: '123'
    #  vm_mac: '52:54:00:3d:11:5f'
    noble-playground:
      host_id: '124'

builder:
  hosts:
    build-1:
      ansible_user: 'adam.richardson'
      is_virtual: no

foreman:
  hosts:
    noble-playground:
  vars:
    foreman_dhcp_range_start_id: '175'
    foreman_dhcp_range_end_id: '195'
    foreman_reverse_zone: '{{ subnet | reverse_zone }}'

# there can be only one
primaries:
  hosts:
    k3s-mother-01:
  vars:
    # in a real production environment we would be happy with 3,
    # just don't define this (it's the default)
    longhorn_number_of_replicas: 1

secondaries:
  hosts:
    k3s-mother-02:
    k3s-mother-03:

agents:
  hosts:
    k3s-child-01:
    k3s-child-02:
    k3s-child-03:
...
# vim: set filetype=yaml:
