---
- name: 'Template in manifest'
  template:
    src: 'issuers.yaml.j2'
    dest: '/dev/shm/issuers.yaml'

- name: 'Set up automatic certificate rotation'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'apply'
      - '-f'
      - '/dev/shm/issuers.yaml'

# TODO: add pause
- name: 'Get the CA certificate in PEM format (for loading into Firefox)'
  register: 'reg_ca_crt'
  command:
    argv:
      - '/usr/local/bin/kubectl'
      - 'get'
      - '-n'
      - '{{ cert_manager_namespace }}'
      - 'secret/{{ ca_secret_name }}'
      - '-o'
      - 'jsonpath="{.data.ca\.crt}"'

- name: 'Dump certificate to a file'
  copy:
    content: '{{ reg_ca_crt.stdout | b64decode }}'
    dest: 'k3s-ca.crt'
...
# vim: set filetype=yaml:
