---
# Things to do manually:
# 1. set up hostname outside the cluster - DNS or hosts file
# 2. copy the k3s-ca.crt outside and install in browsers

# TODO: make script?
- name: 'Set up ingress'
  vars:
    ingress_yaml: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: {{ ingress_prefix }}-ingress
        namespace: {{ ingress_namespace }}
        annotations:
          cert-manager.io/cluster-issuer: {{ certificate_issuer }}
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/ssl-redirect: 'false'
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      spec:
        ingressClassName: nginx
        tls:
        - hosts:
          - {{ ingress_prefix }}.{{ domain }}
          secretName: {{ ingress_prefix }}-tls
        rules:
        - host: {{ ingress_prefix }}.{{ domain }}
          http:
            paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: {{ ingress_service }}
                  port:
                    number: 80
    user: '{{ ingress_user }}'
    password: '{{ lookup("password", "/dev/null", length=16) }}'
  block:
    # Hmm --- secret needs a data.auth section? TODO: verify this, do if so
    - name: 'Create secret'
      environment:
        stdin: '{{ user }}:{{ password | password_hash("sha256") }}'
      command:
        argv:
          - '/usr/local/bin/kubectl'
          - 'create'
          - '-n'
          - '{{ ingress_namespace }}'
          - 'secret'
          - 'generic'
          - 'basic-auth'
          - '-f'
          - '-'

    - name: 'Create ingress'
      environment:
        stdin: '{{ ingress_yaml }}'
      command:
        argv:
          - '/usr/local/bin/kubectl'
          - 'apply'
          - '-n'
          - '{{ ingress_namespace }}'
          - '-f'
          - '-'

    - name: 'Output password'
      copy:
        content: '{{ password }}'
        dest: '{{ ingress_prefix }}-{{ user }}-password.txt'
...
# vim: set filetype=yaml:
