---
# Things to do manually:
# 1. set up hostname outside the cluster - DNS or hosts file
# 2. copy the k3s-ca.crt outside and install in browsers

# TODO #49: make script?
- name: 'Set up ingress'
  vars:
    user: '{{ ingress_user }}'
    pw_file: '{{ ingress_prefix }}-{{ user }}-password.txt'
    # password lookup doesn't work consistently
    #password: '{{ lookup("password", pw_file, length=16) }}'
  block:
    - name: 'Remove old password files'
      file:
        path: '{{ pw_file }}'
        state: 'absent'

    - name: 'Generate password'
      register: 'reg_gen_pw'
      command:
        argv:
          - 'uuidgen'

    - name: 'Write password file'
      copy:
        content: '{{ reg_gen_pw.stdout }}'
        dest: '{{ pw_file }}'

    # HTTP Basic Auth only supports bcrypt, apr1, sha1 or local crypt.
    # Basic Auth is kinda old and crappy.
    - name: 'Hash password'
      register: 'reg_pw_hash'
      vars:
        # TODO: improve this: it's a pepper currently
        salt: 'potatoes'
      command:
        argv:
          - 'openssl'
          - 'passwd'
          - '-salt={{ salt }}'
          - '-apr1'
          - '{{ reg_gen_pw.stdout }}'

    - name: 'Create secret'
      register: 'reg_secret'
      vars:
        e_already: 'already exists'
      failed_when:
        - 'reg_secret.rc != 0'
        - 'e_already not in reg_secret.stderr'
      command:
        argv:
          - '/usr/local/bin/kubectl'
          - 'create'
          - '-n'
          - '{{ ingress_namespace }}'
          - 'secret'
          - 'generic'
          - '{{ secret_name }}'
          - '--from-literal=auth={{ user }}:{{ reg_pw_hash.stdout }}'

    - name: 'Template ingress'
      template:
        src: 'ingress.yaml.j2'
        dest: '/dev/shm/ingress.yaml'

    - name: 'Create ingress'
      command:
        argv:
          - '/usr/local/bin/kubectl'
          - 'apply'
          - '-n'
          - '{{ ingress_namespace }}'
          - '-f'
          - '/dev/shm/ingress.yaml'
...
# vim: set filetype=yaml:
